import 'package:flutter/material.dart';

import '../models/open_app.dart';

class AppIconMatch {
  const AppIconMatch(this.icon, this.color, this.label, [this.assetPath]);

  final IconData icon;
  final Color color;
  final String label;
  final String? assetPath;
}

class AppIconRegistry {
  static const Map<String, AppIconMatch> _icons = {
    'microsoft powerpoint': AppIconMatch(Icons.slideshow, Color(0xFFD24726),
        'PowerPoint', 'assets/app_icons/powerpoint.png'),
    'windows media player': AppIconMatch(Icons.play_arrow, Color(0xFF607D8B),
        'Media Player', 'assets/app_icons/media_player.png'),
    'adobe after effects': AppIconMatch(Icons.animation, Color(0xFF9999FF),
        'After Effects', 'assets/app_icons/after_effects.png'),
    'amazon web services': AppIconMatch(
        Icons.cloud, Color(0xFFFF9900), 'AWS', 'assets/app_icons/aws.png'),
    'amazon prime video': AppIconMatch(Icons.movie_filter, Color(0xFF00A8E1),
        'Prime Video', 'assets/app_icons/prime_video.png'),
    'visual studio code': AppIconMatch(Icons.code, Color(0xFF007ACC), 'VS Code',
        'assets/app_icons/vscode.png'),
    'adobe illustrator': AppIconMatch(Icons.gesture, Color(0xFFFF9A00),
        'Illustrator', 'assets/app_icons/illustrator.png'),
    'internet explorer': AppIconMatch(Icons.explore_outlined, Color(0xFF00A4EF),
        'IE', 'assets/app_icons/internet_explorer.png'),
    'microsoft copilot': AppIconMatch(Icons.smart_toy, Color(0xFF5B5FC7),
        'Copilot', 'assets/app_icons/copilot.png'),
    'microsoft onenote': AppIconMatch(Icons.note_alt, Color(0xFF7719AA),
        'OneNote', 'assets/app_icons/onenote.png'),
    'microsoft outlook': AppIconMatch(Icons.email, Color(0xFF0078D4), 'Outlook',
        'assets/app_icons/outlook.png'),
    'microsoft project': AppIconMatch(Icons.event_note, Color(0xFF31752F),
        'Project', 'assets/app_icons/project.png'),
    'notepad plus plus': AppIconMatch(Icons.code, Color(0xFF4CAF50),
        'Notepad++', 'assets/app_icons/notepad_plus_plus.png'),
    'google translate': AppIconMatch(Icons.translate, Color(0xFF5F6368),
        'Translate', 'assets/app_icons/google_translate.png'),
    'translate.google': AppIconMatch(Icons.translate, Color(0xFF5F6368),
        'Translate', 'assets/app_icons/google_translate.png'),
    'vlc media player': AppIconMatch(Icons.play_circle, Color(0xFFFF8800),
        'VLC', 'assets/app_icons/vlc.png'),
    'windows explorer': AppIconMatch(Icons.folder, Color(0xFFFFC107),
        'Explorer', 'assets/app_icons/file_explorer.png'),
    'windows security': AppIconMatch(Icons.security, Color(0xFF2E7D32),
        'Security', 'assets/app_icons/windows_security.png'),
    'windows terminal': AppIconMatch(Icons.terminal, Color(0xFF212121),
        'Terminal', 'assets/app_icons/terminal.png'),
    'adobe photoshop': AppIconMatch(Icons.photo, Color(0xFF31A8FF), 'Photoshop',
        'assets/app_icons/photoshop.png'),
    'calendar.google': AppIconMatch(Icons.calendar_month, Color(0xFF4285F4),
        'Calendar', 'assets/app_icons/google_calendar.png'),
    'chat.openai.com': AppIconMatch(Icons.auto_awesome, Color(0xFF10A37F),
        'ChatGPT', 'assets/app_icons/chatgpt.png'),
    'electronic arts': AppIconMatch(Icons.sports_esports, Color(0xFFFF6C00),
        'EA', 'assets/app_icons/ea.png'),
    'google calendar': AppIconMatch(Icons.calendar_month, Color(0xFF4285F4),
        'Calendar', 'assets/app_icons/google_calendar.png'),
    'microsoft azure': AppIconMatch(
        Icons.cloud, Color(0xFF0078D4), 'Azure', 'assets/app_icons/azure.png'),
    'microsoft excel': AppIconMatch(Icons.table_chart, Color(0xFF217346),
        'Excel', 'assets/app_icons/excel.png'),
    'microsoft store': AppIconMatch(Icons.store, Color(0xFF0078D4), 'Store',
        'assets/app_icons/microsoft_store.png'),
    'microsoft teams': AppIconMatch(
        Icons.groups, Color(0xFF6264A7), 'Teams', 'assets/app_icons/teams.png'),
    'mozilla firefox': AppIconMatch(Icons.local_fire_department,
        Color(0xFFFF7139), 'Firefox', 'assets/app_icons/firefox.png'),
    'system settings': AppIconMatch(Icons.settings, Color(0xFF607D8B),
        'Settings', 'assets/app_icons/settings.png'),
    'ubisoft connect': AppIconMatch(Icons.sports_esports, Color(0xFF0070FF),
        'Ubisoft', 'assets/app_icons/ubisoft.png'),
    'adobe premiere': AppIconMatch(Icons.movie_creation, Color(0xFF9999FF),
        'Premiere', 'assets/app_icons/premiere.png'),
    'android studio': AppIconMatch(Icons.android, Color(0xFF3DDC84),
        'Android Studio', 'assets/app_icons/android_studio.png'),
    'command prompt': AppIconMatch(
        Icons.terminal, Color(0xFF111111), 'CMD', 'assets/app_icons/cmd.png'),
    'docker desktop': AppIconMatch(Icons.cloud_queue, Color(0xFF2496ED),
        'Docker', 'assets/app_icons/docker.png'),
    'github desktop': AppIconMatch(
        Icons.code, Color(0xFF111111), 'GitHub', 'assets/app_icons/github.png'),
    'microsoft edge': AppIconMatch(Icons.travel_explore, Color(0xFF0AA6B7),
        'Edge', 'assets/app_icons/edge.png'),
    'microsoft word': AppIconMatch(Icons.description, Color(0xFF2B579A), 'Word',
        'assets/app_icons/word.png'),
    'securityhealth': AppIconMatch(Icons.security, Color(0xFF2E7D32),
        'Security', 'assets/app_icons/windows_security.png'),
    'adobe acrobat': AppIconMatch(Icons.picture_as_pdf, Color(0xFFEC1C24),
        'Acrobat', 'assets/app_icons/acrobat.png'),
    'after effects': AppIconMatch(Icons.animation, Color(0xFF9999FF),
        'After Effects', 'assets/app_icons/after_effects.png'),
    'brave browser': AppIconMatch(
        Icons.shield, Color(0xFFFB542B), 'Brave', 'assets/app_icons/brave.png'),
    'control panel': AppIconMatch(Icons.tune, Color(0xFF607D8B),
        'Control Panel', 'assets/app_icons/control_panel.png'),
    'file explorer': AppIconMatch(Icons.folder, Color(0xFFFFC107), 'Explorer',
        'assets/app_icons/file_explorer.png'),
    'gemini.google': AppIconMatch(Icons.diamond, Color(0xFF4285F4), 'Gemini',
        'assets/app_icons/gemini.png'),
    'google chrome': AppIconMatch(Icons.public, Color(0xFF4285F4), 'Chrome',
        'assets/app_icons/chrome.png'),
    'google sheets': AppIconMatch(Icons.table_chart, Color(0xFF0F9D58),
        'Sheets', 'assets/app_icons/google_sheets.png'),
    'google slides': AppIconMatch(Icons.slideshow, Color(0xFFF4B400), 'Slides',
        'assets/app_icons/google_slides.png'),
    'perplexity.ai': AppIconMatch(Icons.travel_explore, Color(0xFF20B2AA),
        'Perplexity', 'assets/app_icons/perplexity.png'),
    'sheets.google': AppIconMatch(Icons.table_chart, Color(0xFF0F9D58),
        'Sheets', 'assets/app_icons/google_sheets.png'),
    'slides.google': AppIconMatch(Icons.slideshow, Color(0xFFF4B400), 'Slides',
        'assets/app_icons/google_slides.png'),
    'visual studio': AppIconMatch(Icons.developer_mode, Color(0xFF5C2D91),
        'Visual Studio', 'assets/app_icons/visual_studio.png'),
    'windows store': AppIconMatch(Icons.store, Color(0xFF0078D4), 'Store',
        'assets/app_icons/microsoft_store.png'),
    'drive.google': AppIconMatch(Icons.cloud, Color(0xFF34A853), 'Drive',
        'assets/app_icons/google_drive.png'),
    'explorer.exe': AppIconMatch(Icons.folder, Color(0xFFFFC107), 'Explorer',
        'assets/app_icons/file_explorer.png'),
    'google drive': AppIconMatch(Icons.cloud, Color(0xFF34A853), 'Drive',
        'assets/app_icons/google_drive.png'),
    'media player': AppIconMatch(Icons.play_arrow, Color(0xFF607D8B),
        'Media Player', 'assets/app_icons/media_player.png'),
    'powerpnt.exe': AppIconMatch(Icons.slideshow, Color(0xFFD24726),
        'PowerPoint', 'assets/app_icons/powerpoint.png'),
    'premiere pro': AppIconMatch(Icons.movie_creation, Color(0xFF9999FF),
        'Premiere', 'assets/app_icons/premiere.png'),
    'sublime text': AppIconMatch(Icons.code, Color(0xFFFF9800), 'Sublime',
        'assets/app_icons/sublime.png'),
    'task manager': AppIconMatch(Icons.monitor_heart, Color(0xFF4CAF50),
        'Task Manager', 'assets/app_icons/task_manager.png'),
    'web.telegram': AppIconMatch(Icons.send, Color(0xFF26A5E4), 'Telegram',
        'assets/app_icons/telegram.png'),
    'web.whatsapp': AppIconMatch(Icons.call, Color(0xFF25D366), 'WhatsApp',
        'assets/app_icons/whatsapp.png'),
    'whatsapp web': AppIconMatch(Icons.call, Color(0xFF25D366), 'WhatsApp',
        'assets/app_icons/whatsapp.png'),
    'bard.google': AppIconMatch(Icons.diamond, Color(0xFF4285F4), 'Gemini',
        'assets/app_icons/gemini.png'),
    'chatgpt.com': AppIconMatch(Icons.auto_awesome, Color(0xFF10A37F),
        'ChatGPT', 'assets/app_icons/chatgpt.png'),
    'docs.google': AppIconMatch(Icons.article, Color(0xFF4285F4), 'Docs',
        'assets/app_icons/google_docs.png'),
    'firefox.exe': AppIconMatch(Icons.local_fire_department, Color(0xFFFF7139),
        'Firefox', 'assets/app_icons/firefox.png'),
    'google docs': AppIconMatch(Icons.article, Color(0xFF4285F4), 'Docs',
        'assets/app_icons/google_docs.png'),
    'google mail': AppIconMatch(
        Icons.mail, Color(0xFFEA4335), 'Gmail', 'assets/app_icons/gmail.png'),
    'google maps': AppIconMatch(Icons.map, Color(0xFF34A853), 'Maps',
        'assets/app_icons/google_maps.png'),
    'illustrator': AppIconMatch(Icons.gesture, Color(0xFFFF9A00), 'Illustrator',
        'assets/app_icons/illustrator.png'),
    'mail.google': AppIconMatch(
        Icons.mail, Color(0xFFEA4335), 'Gmail', 'assets/app_icons/gmail.png'),
    'maps.google': AppIconMatch(Icons.map, Color(0xFF34A853), 'Maps',
        'assets/app_icons/google_maps.png'),
    'notepad.exe': AppIconMatch(Icons.notes, Color(0xFF607D8B), 'Notepad',
        'assets/app_icons/notepad.png'),
    'outlook.exe': AppIconMatch(Icons.email, Color(0xFF0078D4), 'Outlook',
        'assets/app_icons/outlook.png'),
    'prime video': AppIconMatch(Icons.movie_filter, Color(0xFF00A8E1),
        'Prime Video', 'assets/app_icons/prime_video.png'),
    'riot client': AppIconMatch(Icons.sports_esports, Color(0xFFD13639), 'Riot',
        'assets/app_icons/riot.png'),
    'threads.net': AppIconMatch(Icons.forum_outlined, Color(0xFF111111),
        'Threads', 'assets/app_icons/threads.png'),
    'tor browser': AppIconMatch(
        Icons.security, Color(0xFF7D4698), 'Tor', 'assets/app_icons/tor.png'),
    'vivaldi.exe': AppIconMatch(Icons.web, Color(0xFFEF3939), 'Vivaldi',
        'assets/app_icons/vivaldi.png'),
    'winword.exe': AppIconMatch(Icons.description, Color(0xFF2B579A), 'Word',
        'assets/app_icons/word.png'),
    'youtube.com': AppIconMatch(Icons.play_circle_fill, Color(0xFFFF0000),
        'YouTube', 'assets/app_icons/youtube.png'),
    'amazon.com': AppIconMatch(Icons.shopping_cart, Color(0xFFFF9900), 'Amazon',
        'assets/app_icons/amazon.png'),
    'battle.net': AppIconMatch(Icons.sports_esports, Color(0xFF00AEFF),
        'Battle.net', 'assets/app_icons/battle_net.png'),
    'calculator': AppIconMatch(Icons.calculate, Color(0xFF607D8B), 'Calculator',
        'assets/app_icons/calculator.png'),
    'chrome.exe': AppIconMatch(Icons.public, Color(0xFF4285F4), 'Chrome',
        'assets/app_icons/chrome.png'),
    'cloudflare': AppIconMatch(Icons.cloud, Color(0xFFF38020), 'Cloudflare',
        'assets/app_icons/cloudflare.png'),
    'devenv.exe': AppIconMatch(Icons.developer_mode, Color(0xFF5C2D91),
        'Visual Studio', 'assets/app_icons/visual_studio.png'),
    'epic games': AppIconMatch(Icons.sports_esports, Color(0xFF111111),
        'Epic Games', 'assets/app_icons/epic_games.png'),
    'github.com': AppIconMatch(
        Icons.code, Color(0xFF111111), 'GitHub', 'assets/app_icons/github.png'),
    'google.com': AppIconMatch(Icons.search, Color(0xFF4285F4), 'Google',
        'assets/app_icons/google.png'),
    'ms project': AppIconMatch(Icons.event_note, Color(0xFF31752F), 'Project',
        'assets/app_icons/project.png'),
    'msedge.exe': AppIconMatch(Icons.travel_explore, Color(0xFF0AA6B7), 'Edge',
        'assets/app_icons/edge.png'),
    'obs studio': AppIconMatch(Icons.video_camera_front, Color(0xFF111111),
        'OBS', 'assets/app_icons/obs.png'),
    'openai.com': AppIconMatch(Icons.auto_awesome, Color(0xFF10A37F), 'OpenAI',
        'assets/app_icons/openai.png'),
    'perplexity': AppIconMatch(Icons.travel_explore, Color(0xFF20B2AA),
        'Perplexity', 'assets/app_icons/perplexity.png'),
    'postgresql': AppIconMatch(Icons.storage, Color(0xFF336791), 'PostgreSQL',
        'assets/app_icons/postgresql.png'),
    'powerpoint': AppIconMatch(Icons.slideshow, Color(0xFFD24726), 'PowerPoint',
        'assets/app_icons/powerpoint.png'),
    'powershell': AppIconMatch(Icons.terminal, Color(0xFF0277BD), 'PowerShell',
        'assets/app_icons/powershell.png'),
    'python.exe': AppIconMatch(Icons.data_object, Color(0xFF3776AB), 'Python',
        'assets/app_icons/python.png'),
    'anthropic': AppIconMatch(Icons.psychology, Color(0xFF9B6B43), 'Claude',
        'assets/app_icons/claude.png'),
    'battlenet': AppIconMatch(Icons.sports_esports, Color(0xFF00AEFF),
        'Battle.net', 'assets/app_icons/battle_net.png'),
    'bitbucket': AppIconMatch(Icons.source, Color(0xFF0052CC), 'Bitbucket',
        'assets/app_icons/bitbucket.png'),
    'brave.exe': AppIconMatch(
        Icons.shield, Color(0xFFFB542B), 'Brave', 'assets/app_icons/brave.png'),
    'epicgames': AppIconMatch(Icons.sports_esports, Color(0xFF111111),
        'Epic Games', 'assets/app_icons/epic_games.png'),
    'excel.exe': AppIconMatch(Icons.table_chart, Color(0xFF217346), 'Excel',
        'assets/app_icons/excel.png'),
    'instagram': AppIconMatch(Icons.camera_alt, Color(0xFFE4405F), 'Instagram',
        'assets/app_icons/instagram.png'),
    'lightroom': AppIconMatch(Icons.photo_filter, Color(0xFF31A8FF),
        'Lightroom', 'assets/app_icons/lightroom.png'),
    'messenger': AppIconMatch(Icons.message, Color(0xFF0084FF), 'Messenger',
        'assets/app_icons/messenger.png'),
    'minecraft': AppIconMatch(Icons.grass, Color(0xFF62B47A), 'Minecraft',
        'assets/app_icons/minecraft.png'),
    'notepad++': AppIconMatch(Icons.code, Color(0xFF4CAF50), 'Notepad++',
        'assets/app_icons/notepad_plus_plus.png'),
    'one drive': AppIconMatch(Icons.cloud, Color(0xFF0078D4), 'OneDrive',
        'assets/app_icons/onedrive.png'),
    'opera.exe': AppIconMatch(Icons.radio_button_checked, Color(0xFFFF1B2D),
        'Opera', 'assets/app_icons/opera.png'),
    'photoshop': AppIconMatch(Icons.photo, Color(0xFF31A8FF), 'Photoshop',
        'assets/app_icons/photoshop.png'),
    'pinterest': AppIconMatch(Icons.push_pin, Color(0xFFE60023), 'Pinterest',
        'assets/app_icons/pinterest.png'),
    'publisher': AppIconMatch(Icons.menu_book, Color(0xFF077568), 'Publisher',
        'assets/app_icons/publisher.png'),
    'tweetdeck': AppIconMatch(Icons.alternate_email, Color(0xFF111111), 'X',
        'assets/app_icons/x.png'),
    'wordpress': AppIconMatch(Icons.language, Color(0xFF21759B), 'WordPress',
        'assets/app_icons/wordpress.png'),
    'adobe xd': AppIconMatch(Icons.dashboard_customize, Color(0xFFFF61F6),
        'Adobe XD', 'assets/app_icons/adobe_xd.png'),
    'calc.exe': AppIconMatch(Icons.calculate, Color(0xFF607D8B), 'Calculator',
        'assets/app_icons/calculator.png'),
    'code.exe': AppIconMatch(Icons.code, Color(0xFF007ACC), 'VS Code',
        'assets/app_icons/vscode.png'),
    'defender': AppIconMatch(Icons.security, Color(0xFF2E7D32), 'Security',
        'assets/app_icons/windows_security.png'),
    'facebook': AppIconMatch(Icons.facebook, Color(0xFF1877F2), 'Facebook',
        'assets/app_icons/facebook.png'),
    'firebase': AppIconMatch(Icons.local_fire_department, Color(0xFFFFCA28),
        'Firebase', 'assets/app_icons/firebase.png'),
    'fortnite': AppIconMatch(Icons.sports_esports, Color(0xFF3F51B5),
        'Fortnite', 'assets/app_icons/fortnite.png'),
    'git bash': AppIconMatch(
        Icons.merge_type, Color(0xFFF05032), 'Git', 'assets/app_icons/git.png'),
    'idea.exe': AppIconMatch(Icons.code, Color(0xFF6E42C1), 'IntelliJ',
        'assets/app_icons/intellij.png'),
    'iexplore': AppIconMatch(Icons.explore_outlined, Color(0xFF00A4EF), 'IE',
        'assets/app_icons/internet_explorer.png'),
    'intellij': AppIconMatch(Icons.code, Color(0xFF6E42C1), 'IntelliJ',
        'assets/app_icons/intellij.png'),
    'java.exe': AppIconMatch(
        Icons.coffee, Color(0xFFB07219), 'Java', 'assets/app_icons/java.png'),
    'linkedin': AppIconMatch(Icons.business_center, Color(0xFF0A66C2),
        'LinkedIn', 'assets/app_icons/linkedin.png'),
    'msaccess': AppIconMatch(Icons.storage, Color(0xFFA4373A), 'Access',
        'assets/app_icons/access.png'),
    'node.exe': AppIconMatch(
        Icons.hub, Color(0xFF339933), 'Node.js', 'assets/app_icons/nodejs.png'),
    'onedrive': AppIconMatch(Icons.cloud, Color(0xFF0078D4), 'OneDrive',
        'assets/app_icons/onedrive.png'),
    'opera gx': AppIconMatch(Icons.radio_button_checked, Color(0xFFFF1B2D),
        'Opera', 'assets/app_icons/opera.png'),
    'postgres': AppIconMatch(Icons.storage, Color(0xFF336791), 'PostgreSQL',
        'assets/app_icons/postgresql.png'),
    'powerpnt': AppIconMatch(Icons.slideshow, Color(0xFFD24726), 'PowerPoint',
        'assets/app_icons/powerpoint.png'),
    'premiere': AppIconMatch(Icons.movie_creation, Color(0xFF9999FF),
        'Premiere', 'assets/app_icons/premiere.png'),
    'rockstar': AppIconMatch(Icons.star, Color(0xFFFCAF17), 'Rockstar',
        'assets/app_icons/rockstar.png'),
    'settings': AppIconMatch(Icons.settings, Color(0xFF607D8B), 'Settings',
        'assets/app_icons/settings.png'),
    'sketchup': AppIconMatch(Icons.house_siding, Color(0xFFE72B2D), 'SketchUp',
        'assets/app_icons/sketchup.png'),
    'snapchat': AppIconMatch(Icons.photo_camera, Color(0xFFFFFC00), 'Snapchat',
        'assets/app_icons/snapchat.png'),
    'telegram': AppIconMatch(Icons.send, Color(0xFF26A5E4), 'Telegram',
        'assets/app_icons/telegram.png'),
    'terminal': AppIconMatch(Icons.terminal, Color(0xFF212121), 'Terminal',
        'assets/app_icons/terminal.png'),
    'valorant': AppIconMatch(Icons.sports_esports, Color(0xFFFF4655),
        'Valorant', 'assets/app_icons/valorant.png'),
    'webstorm': AppIconMatch(Icons.javascript, Color(0xFF00CDD7), 'WebStorm',
        'assets/app_icons/webstorm.png'),
    'whatsapp': AppIconMatch(Icons.call, Color(0xFF25D366), 'WhatsApp',
        'assets/app_icons/whatsapp.png'),
    'youtu.be': AppIconMatch(Icons.play_circle_fill, Color(0xFFFF0000),
        'YouTube', 'assets/app_icons/youtube.png'),
    '3ds max': AppIconMatch(Icons.view_in_ar, Color(0xFF455A64), '3ds Max',
        'assets/app_icons/3ds_max.png'),
    'acrobat': AppIconMatch(Icons.picture_as_pdf, Color(0xFFEC1C24), 'Acrobat',
        'assets/app_icons/acrobat.png'),
    'autocad': AppIconMatch(Icons.architecture, Color(0xFFE51050), 'AutoCAD',
        'assets/app_icons/autocad.png'),
    'binance': AppIconMatch(Icons.currency_bitcoin, Color(0xFFF3BA2F),
        'Binance', 'assets/app_icons/binance.png'),
    'blender': AppIconMatch(Icons.view_in_ar, Color(0xFFF5792A), 'Blender',
        'assets/app_icons/blender.png'),
    'chatgpt': AppIconMatch(Icons.auto_awesome, Color(0xFF10A37F), 'ChatGPT',
        'assets/app_icons/chatgpt.png'),
    'cmd.exe': AppIconMatch(
        Icons.terminal, Color(0xFF111111), 'CMD', 'assets/app_icons/cmd.png'),
    'copilot': AppIconMatch(Icons.smart_toy, Color(0xFF5B5FC7), 'Copilot',
        'assets/app_icons/copilot.png'),
    'discord': AppIconMatch(Icons.forum, Color(0xFF5865F2), 'Discord',
        'assets/app_icons/discord.png'),
    'disney+': AppIconMatch(Icons.movie, Color(0xFF113CCF), 'Disney+',
        'assets/app_icons/disney_plus.png'),
    'dropbox': AppIconMatch(Icons.cloud_sync, Color(0xFF0061FF), 'Dropbox',
        'assets/app_icons/dropbox.png'),
    'eclipse': AppIconMatch(Icons.code, Color(0xFF2C2255), 'Eclipse',
        'assets/app_icons/eclipse.png'),
    'firefox': AppIconMatch(Icons.local_fire_department, Color(0xFFFF7139),
        'Firefox', 'assets/app_icons/firefox.png'),
    'flutter': AppIconMatch(Icons.flutter_dash, Color(0xFF02569B), 'Flutter',
        'assets/app_icons/flutter.png'),
    'mega.nz': AppIconMatch(Icons.cloud_upload, Color(0xFFD9272E), 'MEGA',
        'assets/app_icons/mega.png'),
    'mongodb': AppIconMatch(Icons.storage, Color(0xFF47A248), 'MongoDB',
        'assets/app_icons/mongodb.png'),
    'mspaint': AppIconMatch(
        Icons.brush, Color(0xFF9C27B0), 'Paint', 'assets/app_icons/paint.png'),
    'netflix': AppIconMatch(Icons.movie, Color(0xFFE50914), 'Netflix',
        'assets/app_icons/netflix.png'),
    'node.js': AppIconMatch(
        Icons.hub, Color(0xFF339933), 'Node.js', 'assets/app_icons/nodejs.png'),
    'notepad': AppIconMatch(Icons.notes, Color(0xFF607D8B), 'Notepad',
        'assets/app_icons/notepad.png'),
    'onenote': AppIconMatch(Icons.note_alt, Color(0xFF7719AA), 'OneNote',
        'assets/app_icons/onenote.png'),
    'outlook': AppIconMatch(Icons.email, Color(0xFF0078D4), 'Outlook',
        'assets/app_icons/outlook.png'),
    'postman': AppIconMatch(Icons.api, Color(0xFFFF6C37), 'Postman',
        'assets/app_icons/postman.png'),
    'pycharm': AppIconMatch(Icons.code, Color(0xFF21D789), 'PyCharm',
        'assets/app_icons/pycharm.png'),
    'shopify': AppIconMatch(Icons.shopping_bag, Color(0xFF7AB55C), 'Shopify',
        'assets/app_icons/shopify.png'),
    'spotify': AppIconMatch(Icons.music_note, Color(0xFF1DB954), 'Spotify',
        'assets/app_icons/spotify.png'),
    'sublime': AppIconMatch(Icons.code, Color(0xFFFF9800), 'Sublime',
        'assets/app_icons/sublime.png'),
    'taskmgr': AppIconMatch(Icons.monitor_heart, Color(0xFF4CAF50),
        'Task Manager', 'assets/app_icons/task_manager.png'),
    'threads': AppIconMatch(Icons.forum_outlined, Color(0xFF111111), 'Threads',
        'assets/app_icons/threads.png'),
    'twitter': AppIconMatch(Icons.alternate_email, Color(0xFF111111), 'X',
        'assets/app_icons/x.png'),
    'ubisoft': AppIconMatch(Icons.sports_esports, Color(0xFF0070FF), 'Ubisoft',
        'assets/app_icons/ubisoft.png'),
    'vivaldi': AppIconMatch(Icons.web, Color(0xFFEF3939), 'Vivaldi',
        'assets/app_icons/vivaldi.png'),
    'winproj': AppIconMatch(Icons.event_note, Color(0xFF31752F), 'Project',
        'assets/app_icons/project.png'),
    'winword': AppIconMatch(Icons.description, Color(0xFF2B579A), 'Word',
        'assets/app_icons/word.png'),
    'wordpad': AppIconMatch(Icons.edit_note, Color(0xFF607D8B), 'WordPad',
        'assets/app_icons/wordpad.png'),
    'youtube': AppIconMatch(Icons.play_circle_fill, Color(0xFFFF0000),
        'YouTube', 'assets/app_icons/youtube.png'),
    '3dsmax': AppIconMatch(Icons.view_in_ar, Color(0xFF455A64), '3ds Max',
        'assets/app_icons/3ds_max.png'),
    'access': AppIconMatch(Icons.storage, Color(0xFFA4373A), 'Access',
        'assets/app_icons/access.png'),
    'amazon': AppIconMatch(Icons.shopping_cart, Color(0xFFFF9900), 'Amazon',
        'assets/app_icons/amazon.png'),
    'chrome': AppIconMatch(Icons.public, Color(0xFF4285F4), 'Chrome',
        'assets/app_icons/chrome.png'),
    'claude': AppIconMatch(Icons.psychology, Color(0xFF9B6B43), 'Claude',
        'assets/app_icons/claude.png'),
    'disney': AppIconMatch(Icons.movie, Color(0xFF113CCF), 'Disney+',
        'assets/app_icons/disney_plus.png'),
    'docker': AppIconMatch(Icons.cloud_queue, Color(0xFF2496ED), 'Docker',
        'assets/app_icons/docker.png'),
    'ea app': AppIconMatch(Icons.sports_esports, Color(0xFFFF6C00), 'EA',
        'assets/app_icons/ea.png'),
    'fb.com': AppIconMatch(Icons.facebook, Color(0xFF1877F2), 'Facebook',
        'assets/app_icons/facebook.png'),
    'gemini': AppIconMatch(Icons.diamond, Color(0xFF4285F4), 'Gemini',
        'assets/app_icons/gemini.png'),
    'github': AppIconMatch(
        Icons.code, Color(0xFF111111), 'GitHub', 'assets/app_icons/github.png'),
    'gitlab': AppIconMatch(Icons.merge, Color(0xFFFC6D26), 'GitLab',
        'assets/app_icons/gitlab.png'),
    'google': AppIconMatch(Icons.search, Color(0xFF4285F4), 'Google',
        'assets/app_icons/google.png'),
    'idea64': AppIconMatch(Icons.code, Color(0xFF6E42C1), 'IntelliJ',
        'assets/app_icons/intellij.png'),
    'msedge': AppIconMatch(Icons.travel_explore, Color(0xFF0AA6B7), 'Edge',
        'assets/app_icons/edge.png'),
    'openai': AppIconMatch(Icons.auto_awesome, Color(0xFF10A37F), 'OpenAI',
        'assets/app_icons/openai.png'),
    'paypal': AppIconMatch(Icons.payments, Color(0xFF003087), 'PayPal',
        'assets/app_icons/paypal.png'),
    'python': AppIconMatch(Icons.data_object, Color(0xFF3776AB), 'Python',
        'assets/app_icons/python.png'),
    'reddit': AppIconMatch(Icons.forum, Color(0xFFFF4500), 'Reddit',
        'assets/app_icons/reddit.png'),
    'roblox': AppIconMatch(Icons.extension, Color(0xFF607D8B), 'Roblox',
        'assets/app_icons/roblox.png'),
    'safari': AppIconMatch(Icons.explore, Color(0xFF006CFF), 'Safari',
        'assets/app_icons/safari.png'),
    'stripe': AppIconMatch(Icons.credit_card, Color(0xFF635BFF), 'Stripe',
        'assets/app_icons/stripe.png'),
    'tiktok': AppIconMatch(Icons.music_note, Color(0xFF111111), 'TikTok',
        'assets/app_icons/tiktok.png'),
    'twitch': AppIconMatch(Icons.live_tv, Color(0xFF9146FF), 'Twitch',
        'assets/app_icons/twitch.png'),
    'vscode': AppIconMatch(Icons.code, Color(0xFF007ACC), 'VS Code',
        'assets/app_icons/vscode.png'),
    'winrar': AppIconMatch(Icons.archive, Color(0xFF7B1FA2), 'WinRAR',
        'assets/app_icons/winrar.png'),
    'wt.exe': AppIconMatch(Icons.terminal, Color(0xFF212121), 'Terminal',
        'assets/app_icons/terminal.png'),
    '7-zip': AppIconMatch(Icons.folder_zip, Color(0xFF607D8B), '7-Zip',
        'assets/app_icons/seven_zip.png'),
    'azure': AppIconMatch(
        Icons.cloud, Color(0xFF0078D4), 'Azure', 'assets/app_icons/azure.png'),
    'brave': AppIconMatch(
        Icons.shield, Color(0xFFFB542B), 'Brave', 'assets/app_icons/brave.png'),
    'canva': AppIconMatch(Icons.palette, Color(0xFF00C4CC), 'Canva',
        'assets/app_icons/canva.png'),
    'excel': AppIconMatch(Icons.table_chart, Color(0xFF217346), 'Excel',
        'assets/app_icons/excel.png'),
    'figma': AppIconMatch(Icons.design_services, Color(0xFFA259FF), 'Figma',
        'assets/app_icons/figma.png'),
    'gmail': AppIconMatch(
        Icons.mail, Color(0xFFEA4335), 'Gmail', 'assets/app_icons/gmail.png'),
    'mongo': AppIconMatch(Icons.storage, Color(0xFF47A248), 'MongoDB',
        'assets/app_icons/mongodb.png'),
    'mspub': AppIconMatch(Icons.menu_book, Color(0xFF077568), 'Publisher',
        'assets/app_icons/publisher.png'),
    'mysql': AppIconMatch(Icons.storage, Color(0xFF00758F), 'MySQL',
        'assets/app_icons/mysql.png'),
    'opera': AppIconMatch(Icons.radio_button_checked, Color(0xFFFF1B2D),
        'Opera', 'assets/app_icons/opera.png'),
    'paint': AppIconMatch(
        Icons.brush, Color(0xFF9C27B0), 'Paint', 'assets/app_icons/paint.png'),
    'revit': AppIconMatch(Icons.apartment, Color(0xFF0066B3), 'Revit',
        'assets/app_icons/revit.png'),
    'skype': AppIconMatch(Icons.video_call, Color(0xFF00AFF0), 'Skype',
        'assets/app_icons/skype.png'),
    'slack': AppIconMatch(
        Icons.tag, Color(0xFF611F69), 'Slack', 'assets/app_icons/slack.png'),
    'steam': AppIconMatch(Icons.sports_esports, Color(0xFF1B2838), 'Steam',
        'assets/app_icons/steam.png'),
    'store': AppIconMatch(Icons.store, Color(0xFF0078D4), 'Store',
        'assets/app_icons/microsoft_store.png'),
    'teams': AppIconMatch(
        Icons.groups, Color(0xFF6264A7), 'Teams', 'assets/app_icons/teams.png'),
    'visio': AppIconMatch(Icons.account_tree, Color(0xFF3955A3), 'Visio',
        'assets/app_icons/visio.png'),
    'x.com': AppIconMatch(Icons.alternate_email, Color(0xFF111111), 'X',
        'assets/app_icons/x.png'),
    '7zip': AppIconMatch(Icons.folder_zip, Color(0xFF607D8B), '7-Zip',
        'assets/app_icons/seven_zip.png'),
    'atom': AppIconMatch(Icons.data_object, Color(0xFF4CAF50), 'Atom',
        'assets/app_icons/atom.png'),
    'dart': AppIconMatch(
        Icons.code, Color(0xFF0175C2), 'Dart', 'assets/app_icons/dart.png'),
    'ebay': AppIconMatch(Icons.shopping_cart, Color(0xFF0064D2), 'eBay',
        'assets/app_icons/ebay.png'),
    'edge': AppIconMatch(Icons.travel_explore, Color(0xFF0AA6B7), 'Edge',
        'assets/app_icons/edge.png'),
    'hulu': AppIconMatch(
        Icons.live_tv, Color(0xFF1CE783), 'Hulu', 'assets/app_icons/hulu.png'),
    'java': AppIconMatch(
        Icons.coffee, Color(0xFFB07219), 'Java', 'assets/app_icons/java.png'),
    'mega': AppIconMatch(Icons.cloud_upload, Color(0xFFD9272E), 'MEGA',
        'assets/app_icons/mega.png'),
    'node': AppIconMatch(
        Icons.hub, Color(0xFF339933), 'Node.js', 'assets/app_icons/nodejs.png'),
    'pubg': AppIconMatch(Icons.sports_esports, Color(0xFFF2A900), 'PUBG',
        'assets/app_icons/pubg.png'),
    'pwsh': AppIconMatch(Icons.terminal, Color(0xFF0277BD), 'PowerShell',
        'assets/app_icons/powershell.png'),
    'riot': AppIconMatch(Icons.sports_esports, Color(0xFFD13639), 'Riot',
        'assets/app_icons/riot.png'),
    'word': AppIconMatch(Icons.description, Color(0xFF2B579A), 'Word',
        'assets/app_icons/word.png'),
    'zoom': AppIconMatch(
        Icons.videocam, Color(0xFF2D8CFF), 'Zoom', 'assets/app_icons/zoom.png'),
    'aws': AppIconMatch(
        Icons.cloud, Color(0xFFFF9900), 'AWS', 'assets/app_icons/aws.png'),
    'cmd': AppIconMatch(
        Icons.terminal, Color(0xFF111111), 'CMD', 'assets/app_icons/cmd.png'),
    'git': AppIconMatch(
        Icons.merge_type, Color(0xFFF05032), 'Git', 'assets/app_icons/git.png'),
    'obs': AppIconMatch(Icons.video_camera_front, Color(0xFF111111), 'OBS',
        'assets/app_icons/obs.png'),
    'pdf': AppIconMatch(Icons.picture_as_pdf, Color(0xFFEC1C24), 'Acrobat',
        'assets/app_icons/acrobat.png'),
    'rar': AppIconMatch(Icons.archive, Color(0xFF7B1FA2), 'WinRAR',
        'assets/app_icons/winrar.png'),
    'tor': AppIconMatch(
        Icons.security, Color(0xFF7D4698), 'Tor', 'assets/app_icons/tor.png'),
    'vlc': AppIconMatch(Icons.play_circle, Color(0xFFFF8800), 'VLC',
        'assets/app_icons/vlc.png'),
    'zip': AppIconMatch(Icons.folder_zip, Color(0xFF607D8B), '7-Zip',
        'assets/app_icons/seven_zip.png'),
    'xd': AppIconMatch(Icons.dashboard_customize, Color(0xFFFF61F6), 'Adobe XD',
        'assets/app_icons/adobe_xd.png'),
  };

  static final List<MapEntry<String, AppIconMatch>> _orderedIcons =
      _icons.entries.toList()
        ..sort((a, b) => b.key.length.compareTo(a.key.length));

  static AppIconMatch match(OpenApp app) => matchText(app.effectiveIconKey);

  static AppIconMatch matchText(String text) {
    final lower = text.toLowerCase();
    for (final entry in _orderedIcons) {
      if (lower.contains(entry.key)) return entry.value;
    }
    return const AppIconMatch(Icons.apps, Color(0xFF607D8B), 'App');
  }

  static Uri? faviconUrl(OpenApp app, {int size = 64}) {
    final source = (app.url ?? app.siteName ?? '').trim();
    if (source.isEmpty) return null;
    final uri = _tryParseUrl(source);
    final host = uri?.host.trim();
    if (host == null || host.isEmpty || !host.contains('.')) return null;
    return Uri.https('www.google.com', '/s2/favicons', {
      'domain': host,
      'sz': size.toString(),
    });
  }

  static Uri? _tryParseUrl(String value) {
    var text = value.trim();
    if (text.isEmpty) return null;
    if (!text.contains('://') && text.contains('.')) {
      text = 'https://$text';
    }
    return Uri.tryParse(text);
  }

  static int get knownIconCount => 139;
  static int get knownAliasCount => _icons.length;
}
